CREATE TABLE [Admin].[Links]
(
	 LinkId			INT				NOT NULL	IDENTITY(1,1) PRIMARY KEY
	,LinkShort		NVARCHAR(256)	NOT NULL
	,LinkOrig		NVARCHAR(MAX)	NOT NULL
	,CreatedBy		NVARCHAR(257)	NOT NULL
	,CreatedDate	DATETIME2(7)	NOT NULL
	,UpdatedBy		NVARCHAR(257)	NOT NULL
	,UpdatedDate	DATETIME2(7)	NOT NULL
)
